spring.application.name=lottery-system


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

ticket.random.lines.max = 5


# JPA and Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

